name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 0.3.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^3.0.0
  image_picker:
    git: 
      url: https://github.com/hetian9288/image_picker.git
  quill_delta: ^1.0.0-dev.1.0
#  notus: ^0.1.0
  meta: ^1.1.0
  crypto: ^2.0.6
  notus:
      path: ../notus

dev_dependencies:
  flutter_test:
    sdk: flutter
